'use strict';function m(a,b,c,e){var g=arguments.length,d=3>g?b:null===e?e=Object.getOwnPropertyDescriptor(b,c):e,f;if("object"===typeof Reflect&&Reflect&&"function"===typeof Reflect.decorate)d=Reflect.decorate(a,b,c,e);else for(var k=a.length-1;0<=k;k--)if(f=a[k])d=(3>g?f(d):3<g?f(b,c,d):f(b,c))||d;3<g&&d&&Object.defineProperty(b,c,d)};var aa=class{constructor(a){this.b=a}};var ba=class extends Error{};function n(a,b){if(a.h)a.g.push(b);else throw new ba(b);}function p(a,b){a.b=a.b.slice(b)}function q(a,b){return a.b[0]!==b}function r(a){q(a,"=")&&(a.c.T=a.b.slice(0,5),p(a,5))}
var u=class{constructor(a){this.b=a;this.c=Object.create(null)}},ca=class extends u{constructor(a){super(a.replace(/\s/g,""))}f(a=!1){a&&(this.h=!0,this.g=[]);a=this.b.slice(0,4);p(this,4);"AAXX"!==a&&n(this,`Unrecognized header: ${a}.`);q(this,"=")&&(this.c.ta=this.b[4],p(this,5));r(this);q(this,"=")&&(this.c.sa=this.b[0],this.c.va=this.b[1],this.c.qa=this.b[2],this.c.la=this.b.slice(3,5),p(this,5));q(this,"=")&&(this.c.N=this.b[0],this.c.na=this.b.slice(1,3),this.c.l=this.b.slice(3,5),p(this,5));
q(this,"0")||("0"!==this.b[1]?(a=this.b.slice(0,5),p(this,5),n(this,`Unrecognized 0-group ${a}.`)):("99"!==this.c.l&&n(this,"00fff group is present without 99being reported in Nddff group."),this.c.l=this.b.slice(2,5),p(this,5)));q(this,"1")||(this.c.ia=this.b.slice(1,5),p(this,5));q(this,"2")||(this.c.ja=this.b.slice(1,5),p(this,5));q(this,"3")||p(this,5);q(this,"4")||(this.c.ga=this.b.slice(1,5),p(this,5));q(this,"5")||(this.c.a=this.b[1],"9"===this.c.a&&n(this,`Unrecognized 5-group "a" value ${this.c.a}.`),
this.c.ua=this.b.slice(2,5),p(this,5));a=this.c.sa;q(this,"6")?"0"!==a&&"1"!==a||n(this,`6-group is not present, but iR is ${a}.`):("0"!==a&&"1"!==a&&n(this,`6-group is present, but iR is ${a}.`),this.c.ha=this.b.slice(1,5),p(this,5));q(this,"7")||(this.c.ww=this.b.slice(1,3),this.c.W1W2=this.b.slice(3,5),p(this,5));q(this,"8")||(this.c.fa=this.b[1],this.c.X=this.b.slice(2,5),p(this,5));q(this,"9")||p(this,5);{a=this.b[0];let b=this.b.slice(0,3);"222"!==b&&"333"!==b&&"555"!==b&&"="!==a&&0!==this.b.length&&
(a=this.b,n(this,`Unrecognized code ${7>=a.length?a:a.substr(0,5)+".."} after section 1.`))}return this.c}},da=class extends u{constructor(a,b){super(a);a=v.includes(b)?1E3===b?"00":String(b/10|0):void 0;this.i=a;if(!this.i)throw Error("Invalid pressure level "+b);}f(a=!1){a&&(this.h=!0,this.g=[]);q(this,"=")&&(this.c.ma=this.b.substr(0,2),p(this,5));r(this);a:{for(a=this.i;this.b.substr(0,2)!==a;){if("51515"===this.b.substr(0,5)||void 0===this.b[5])break a;p(this,15)}this.c.ra=this.b.substr(2,3);
this.c.ka=this.b.substr(5,3);this.c.Z=this.b.substr(8,2);this.c.oa=this.b.substr(10,3);this.c.l=this.b.substr(13,2)}return this.c}},v=[1E3,925,850,700,500,400,300,250,200,150,100];function w(a,b){return JSON.parse(a.b.getItem(b))}function z(a,b,c){a.b.setItem(b,JSON.stringify(c))}function A(a,b){a=w(a,B);return a[a.length-1-b]}function ea(a,b){b=A(a,b);return[b,JSON.parse(a.b.getItem(D+"."+String(b)))]}function fa(a,b){return a.i(A(a,b))}function ha(a){var b=ia;return w(a,B).slice(-b).reverse().map(a.i,a)}
function ja(a,b,c){a.f&&(a.f.abort(),a.f=void 0);var e=w(a,B);let g=e.length;for(;g--;){let f=e[g],k=a.i(f);if(k.block===b&&k.date===c)return Promise.resolve([f,JSON.parse(a.b.getItem(D+"."+String(f)))])}e=0===(b.endsWith("hPa")?1:0)?E+ka+"block="+encodeURIComponent(b)+"&time="+c:E+la+"time="+c;let d=a.f=new XMLHttpRequest;d.open("GET",e);return new Promise((f,k)=>{d.onreadystatechange=()=>{if(4===d.readyState)if(a.f=void 0,d.onreadystatechange=null,200===d.status){let t=d.responseText.split("\n");
{var h=t;a:{var l=w(a,B);for(let x=0,C=l.length;x<=C;x++)if(-1===l.indexOf(x)){l.push(x);z(a,B,l);l=x;break a}l=void 0}let y={block:b,date:c,queryDate:Date.now()};a.b.setItem(F+"."+String(l),JSON.stringify(y));a.b.setItem(D+"."+String(l),JSON.stringify(h));z(a,G+"."+String(l),0);h=l}f([h,t])}else k(`Error fetching resources: ${d.responseText}, ${d.status}`)};d.send()})}function ma(a,b,c){a.h=b;a.j=c;a.c=new aa(w(a,H+"."+String(b))||[])}function I(a){return w(a,G+"."+String(a.h))}
var na=class{constructor(){this.b=window.localStorage;this.g=!1;null===w(this,B)&&z(this,B,[])}i(a){return w(this,F+"."+String(a))}},F="h",G="curr",B="id",D="rep",H="mark",E="https://synop-api.herokuapp.com/",ka="getsynop-dev?key=XDb34V8MKt6EZY87&",la="gettemp?",oa=/^(?:\d{1,5}|\d{1,5}\-\d{1,5})(?:,\d{1,5}|\d{1,5}\-\d{1,5})*$/,pa=v.map(String);function J(a){return"undefined"===typeof a}function qa(a,b){function c(){Reflect.apply(a,b,e);e=void 0}let e;return function(){let g=J(e);e=arguments;g&&requestAnimationFrame(c)}};function K(a,b){a.U.add(b)}var L=class{constructor(a){this.pa=a;this.U=new Set;this.O=new WeakMap}V(a){this.U.forEach(b=>{try{b(a)}catch(c){}})}handleEvent(a){a.isTrusted&&({currentTarget:a}=a,a=this.O.get(a),J(a)||a.forEach(this.V,this))}L(a,b){let c=this.O.get(a);J(c)&&(c=new Set,this.O.set(a,c),a.addEventListener(this.pa,this));c.add(b)}};function M(a){let b=ha(a.model),c=new L("click"),e=new L("click");K(c,g=>{let {block:d,date:f}=fa(a.model,g),[k,h]=ea(a.model,g);ra(a,k,d,f,h).catch(l=>{sa(a,String(l))})});K(e,g=>{var d=a.model;var f=w(d,B);g=f.splice(-g-1,1)[0];z(d,B,f);f=g;d.b.removeItem(F+"."+String(f));d.b.removeItem(D+"."+String(f));d.b.removeItem(G+"."+String(f));d.b.removeItem(H+"."+String(f));M(a)});ta(a.b,b,c,e)}
function ua(a,b){var c=a.model,e=c.c;e.b[b>>5]^=1<<(b&31);z(c,H+"."+String(c.h),c.c.b);c=a.b;b=c.R.children[b];b.classList.contains("marked")?(b.removeChild(b.getElementsByClassName(va)[0]),b.classList.remove(wa)):(b.appendChild(xa(c)),b.classList.add("marked"));N(a,I(a.model))}
async function ra(a,b,c,e,g){ya(a.b);a.b.g.value=c;a.b.c.value=e;za(a.b);ma(a.model,b,g);await a.b.ba;b=new L("click");Aa(a.b,g,c,a.model.c,b);K(b,d=>{ua(a,d)});await Ba(a.b);a.model.g=!0;M(a);Ca(a.b,a.g);N(a,0);c=I(a.model);null!==c&&Da(a.b,c)}function sa(a,b){Ea(a);requestAnimationFrame(()=>{var c=a.b;c.h.textContent=b;c.h.classList.toggle(Fa,!0)})}function Ga(a,b){Ea(a);requestAnimationFrame(()=>{var c=a.b;c.h.textContent=b;c.h.classList.toggle(Ha,!0)})}
function N(a,b){{var c=a.model.c;let g=0;for(let d=0,f=c.b.length;d<f;d++){{var e=c.b[d];let k=0;for(;0!==e;)e&=e-1,k++;e=k}g+=e}c=g}b=`<span>${b+1}/${a.model.j.length} </span>`;c&&(b+=`<span class="slide__index--marked">${c}&#10003;</span>`);a.b.ca.innerHTML=b}function Ea(a){Ia(a.b);J(a.h)||clearTimeout(a.h);a.h=window.setTimeout(()=>{Ia(a.b)},Ja)}
var La=class{constructor(a,b){this.model=a;this.b=b;this.f=this.f.bind(this);this.c=this.c.bind(this);this.g=qa(this.g,this)}async f(){let a=this.b.g.value;if(oa.test(a)||1===(a.endsWith("hPa")?1:0)&&pa.includes(a.slice(0,-3))){var b=this.b.c.value;if(8===b.length&&/^\d*$/.test(b)){b.slice(0,2);var c=parseInt(b.slice(2,4));var e=parseInt(b.slice(4,6)),g=parseInt(b.slice(6,8));c=12<c||31<e||23<g?!1:!0}else c=!1;if(c){O(this.b,!0);try{const [d,f]=await ja(this.model,a,b);O(this.b,!1);return ra(this,
d,a,b,f)}catch(d){O(this.b,!1),sa(this,String(d))}}else Ga(this,"Please provide the time in a format YYMMDDHH.")}else Ga(this,"Please provide the request block in a form 111,22000-22999.")}g(a){this.b.P(this.model.j[a]);N(this,a);var b=this.model;z(b,G+"."+String(b.h),a)}c(){Ka(this.b);this.model.g=!1}},ia=5,Ja=3E3;function P(a,b,c){const e=c.value;c.value=function(){this.b.save();this.b.translate(this.x,this.y);this.b.scale(this.c,this.c);let g=Reflect.apply(e,this,arguments);this.b.restore();return g}}function Q(a,b=Ma){a.b.font=b;a.b.textBaseline="middle";a.b.textAlign="center"}
var W=class{constructor(a,b,c,e=1){this.b=a;this.x=b;this.y=c;this.c=e}o(a){let b=this.b;b.translate(-R,-R);if(S(a))wxSym.TotalCloudCover.N[a](b);else wxSym.TotalCloudCover.N.Slash(b)}s(a,b){let c=Math.round(b/5),e=this.b;0===b?(e.translate(-32.7,-32.7),wxSym.WindArrowCalm["00"](e)):(e.rotate(a+.5*Math.PI),isNaN(b)?(e.translate(-Na-R+1,-31),wxSym.WindArrowMissing["99"](e)):(e.translate(-Na+2.5-R,-T+7),wxSym.WindArrowNH[String(c).padStart(2,"0")](e)))}B(a,b,c,e){if(!J(a)){var g=this.b,d=a[0],f=a[1],
k=a[2];c=S(c)?parseInt(c):null;a=S(b)?parseInt(b):null;d=S(d)?parseInt(d):null;f=S(f)?parseInt(f):null;k=S(k)?parseInt(k):null;null!==a&&(g.save(),Q(this),g.fillText(b,U-.5*R,U),g.restore());b=()=>{Q(this,"normal 36px American Typewriter, serif");g.fillText("M",R,R)};var h=9===a||9===c;g.save();g.translate(-R,U-R);if(null!==d){if(0!==d)wxSym.CloudLow.CL[d](g)}else h||b();g.restore();g.save();g.translate(-R,-U-R);if(null!==f){if(0!==f)wxSym.CloudMedium.CM[f](g)}else h||8===a&&8===c&&null!==d||b();
g.restore();g.save();g.translate(-R,-2*U-R);if(null!==k){if(0!==k)wxSym.CloudHigh.CH[k](g)}else!h&&(8!==c||7>a||8>a&&(0===d||0===f))&&b();g.restore();g.save();Q(this);g.fillText(e,0,2*U);g.restore()}}D(a){S(a)&&(Q(this),this.b.fillText(a.slice(1),U,-U))}G(a,b){let c=this.b;S(a)&&9>parseInt(a)&&(c.save(),c.translate(2*U-R,-R),wxSym.PressureTendencyCharacteristic.a[a](c),c.restore(),S(b)&&(a=parseInt(a),b=(4>a?"+":4<a?"-":"\u00b1")+b.slice(-2),c.save(),Q(this),c.fillText(b,U,0),c.restore()))}K(a,b){let c=
this.b;c.save();c.translate(-U-R,-R);if(!J(a))if(S(a))wxSym.PresentWeather.ww[a](c);else wxSym.PresentWeather.ww.DoubleSlash(c);c.restore();c.save();c.translate(U-R+1/3*U,U-R);if(!J(b))if(S(b)){if(a=parseInt(b.charAt(0)),b=parseInt(b.slice(1)),b=a>b?a:b,3<=b)wxSym.PastWeather.W1W2[3===b?"3a":String(b)](c)}else wxSym.PastWeather.W1W2.DoubleSlash(c);c.restore()}H(a,b){function c(g){var d=parseInt(g);g=d%1E3;d=(d-g)/1E3;let f=0===d?1:-1;return(0===d?"+":"-")+String(Math.round(f*g/10)*f).padStart(2,"0")}
let e=this.b;Q(this);S(a)&&e.fillText(c(a),-U,-U);S(b)&&e.fillText(c(b),-U,U)}J(a){let b=this.b;S(a)&&(a=parseInt(a),a=50>=a?100*a:80>=a?1E3*(a-50):89>=a?5E3*(a-80)+3E4:[0,50,200,500,1E3,2E3,4E3,1E4,2E4,5E4][a-90],a=500>=a?V(a/100,16):3200>=a?V(a/200,8):4800>=a?V(a/400,4):24E3>=a?String(Math.floor(a/1600)):String(Math.min(5*Math.floor(a/1600/5))),b.translate(2*-U,0),Q(this),b.fillText(a,0,0))}C(a){if(!J(a)){var b=this.b,c=a.slice(0,3);a=a[3];S(c)&&(Q(this),b.fillText(c,U,2*U));S(a)&&(Q(this),b.fillText(a,
2*U,U))}}m(a){let b=this.b;b.textAlign="start";b.textBaseline="middle";b.font="normal 20px Trebuchet MS, sans-serif";const c=b.measureText(a).width;b.fillStyle="black";b.fillRect(-200,-200,c+10,Oa);b.fillStyle="white";b.fillText(a,-195,-200+Oa/2)}I(a,b){let c=this.b;Q(this);S(a)&&(a=(0===(parseInt(a)&1)?"":"-")+parseInt(a.slice(0,2))+"."+a[2],c.fillText(a,-U,-U));S(b)&&(a=parseInt(b),c.fillText(50<a?String(a-50)+".0":b[0]+"."+b[1],-U,U))}F(a){S(a)&&(Q(this),this.b.fillText(a,U,0))}},T=55,R=T/2,Na=
3*T,U=65,Ma="100 36px Optima, sans-serif",Oa=26;m([P],W.prototype,"o",null);m([P],W.prototype,"s",null);m([P],W.prototype,"B",null);m([P],W.prototype,"D",null);m([P],W.prototype,"G",null);m([P],W.prototype,"K",null);m([P],W.prototype,"H",null);m([P],W.prototype,"J",null);m([P],W.prototype,"C",null);m([P],W.prototype,"m",null);m([P],W.prototype,"I",null);m([P],W.prototype,"F",null);
function V(a,b){for(a|=0;0===a%2&&0===b%2;)a/=2,b/=2;let c=0;for(;a>=b;)c++,a-=b;let e=[];if(0===c&&0===a)return"0";0<c&&e.push(String(c));0<a&&e.push(String(a)+"/"+String(b));return e.join(" ")}function S(a){return"string"!==typeof a?!1:/^\d+$/.test(a)};function Pa(a){a.setTransform(1,0,0,1,0,0);a.clearRect(0,0,a.canvas.width,a.canvas.height)}var Qa=class{constructor(a){this.f=a;this.b=[];this.c=[]}};var Ra=Glide;var X=timeago;X.register("en_short",function(a,b){return[["just now","right now"],["%ss ago","in %ss"],["1m ago","in 1m"],["%sm ago","in %sm"],["1h ago","in 1h"],["%sh ago","in %sh"],["1d ago","in 1d"],["%sd ago","in %sd"],["1w ago","in 1w"],["%sw ago","in %sw"],["1mo ago","in 1mo"],["%smo ago","in %smo"],["1yr ago","in 1yr"],["%syr ago","in %syr"]][b]});function Sa(a,b){a.j.addEventListener("click",b);const c=e=>{13===e.keyCode&&b()};a.g.addEventListener("keypress",c);a.c.addEventListener("keypress",c)}
function Ta(a,b){a.b.addEventListener("keydown",c=>{" "===c.key&&b()})}
function ta(a,b,c,e){const g=500>a.b.defaultView.innerWidth;X.cancel();a.v.innerHTML=b.reduce((d,f,k)=>{k=`<div class="query" data-index="${k}">`+'<div class="query__string">'+`<div>${f.block}</div>`;{var h=f.date;var l=parseInt(h.slice(0,2));let t=parseInt(h.slice(2,4)),y=parseInt(h.slice(4,6));h=parseInt(h.slice(6,8));let x=new Date(0);x.setUTCFullYear(70>l?2E3+l:1900+l,t-1,y);x.setUTCHours(h);l=Intl.DateTimeFormat("default",{hour12:!1,year:"2-digit",month:g?"numeric":"short",day:"numeric",hour:"numeric",
timeZone:"UTC",timeZoneName:g?void 0:"short"}).format(x)}f=k+`<div>(${l})</div>`+"</div><div>"+`<div class="query__date" datetime="${(new Date(f.queryDate)).toISOString()}">`+'</div><div class="query__delete"><img src="/static/outline-clear-24px.svg" width="18" height="18"></img></div></div></div>';return d+f},"");X.render(a.v.querySelectorAll(".query__date"),g?"en_short":"en_US");a.v.querySelectorAll(".query__string").forEach(c.L,c);a.v.querySelectorAll(".query__delete").forEach(e.L,e)}
function O(a,b){a.j.classList.toggle("loading",b)}function ya(a){a.f&&a.f.destroy();a.f=void 0;var b=a.u;b.b.forEach(Pa);Array.prototype.push.apply(b.c,b.b);b.b.length=0;a.R.innerHTML="";a.M.classList.toggle("initialized",!1)}function za(a){a.g.blur();a.c.blur()}
function Aa(a,b,c,e,g){for(let y=0,x=b.length;y<x;y++){let C=a.b.createElement("div");C.classList.add("glide__slide");a.R.appendChild(C);a:{var d=void 0;var f=a.u;if(0<f.c.length){d=f.c.pop();var k=f,h=d.canvas;h.width=k.width;h.height=k.height}else if(d=f.f.createElement("canvas"),k=f,h=d,h.width=k.width,h.height=k.height,d=d.getContext("2d"),null===d){f=null;break a}f.b.push(d);f=d}if(f){C.appendChild(f.canvas);k=new W(f,a.i/2,a.i/2,a.i/Y);if(0===(c.endsWith("hPa")?1:0)){f=new ca(b[y]);h=f.f(!0);
k.m(h.T);k.J(h.la);k.o(h.N);var l=h.na,t=h.l;d=h.ta;S(l)&&S(t)&&S(d)&&(l=parseInt(l),t=parseInt(t),50<l&&(l-=50,t+=50),2>parseInt(d)&&(t*=1.94384),k.s(l/36*Math.PI*2,t));k.H(h.ia,h.ja);k.D(h.ga);k.G(h.a,h.ua);k.C(h.ha);k.K(h.ww,h.W1W2);k.B(h.X,h.fa,h.N,h.qa)}else f=new da(b[y],parseInt(c.slice(0,-3))),h=f.f(!0),k.m(h.T),k.F(h.ra),k.o("9"),t=h.oa,d=h.l,S(t)&&S(d)&&(t=parseInt(t),l=t%5,d=parseInt(d)+100*l,50>=parseInt(h.ma)&&(d*=1.94384),k.s((t-l)/360*Math.PI*2,d)),k.I(h.ka,h.Z);f=f.g;f.length&&C.appendChild(Ua(a,
f.join(" ")));if(f=(f=e.b[y>>5])?0!==(f&1<<(y&31)):!1)f=C,f.appendChild(xa(a)),f.classList.add("marked");g.L(C,y)}else C.appendChild(Ua(a,"Couldn't create more canvas to draw on. "+`Currently ${a.u.b.length} canvases are in use. `+"Try refreshing the page."))}}function Ba(a){a.S.classList.toggle(Va,!0);let b=a.b.body.classList;if(!b.contains(Z))return b.toggle(Z,!0),a.g.disabled=a.c.disabled=!0,Wa(a)}
function Ca(a,b){let c=a.f=new Ra(".glide"),e=!1;c.on("mount.after",()=>{e||(e=!0,a.M.classList.toggle("initialized",!0))});c.on("move.after",()=>{let g=a.f.index;"number"===typeof g&&b(g)});c.mount()}function Da(a,b){a.f&&a.f.index!==b&&a.f.go(`=${b}`)}async function Ka(a){let b=a.b.body.classList;b.contains(Z)&&(b.toggle(Z,!1),a.g.disabled=a.c.disabled=!1,await Wa(a),a.S.classList.toggle(Va,!1))}function Ia(a){a=a.h.classList;a.toggle(Fa,!1);a.toggle(Ha,!1)}
function Xa(a){const b=a.b.defaultView;b.addEventListener("resize",a.A);b.addEventListener("orientationchange",a.A)}async function Wa(a){await new Promise(a.da);await new Promise(Ya)}function Ua(a,b){let c=a.b.createElement("div");c.classList.add("slide--error");c.textContent=b;c.style.transform=`scale(${a.i/Y})`;return c}function xa(a){a=a.b.createElement("img");a.classList.add(va);a.src=Za;return a}
var $a=class{constructor(a){this.b=a;this.Y=(new FontFace("American Typewriter",'local(American Typewriter), url(static/sub.woff) format("woff")')).load().then(b=>{this.b.fonts.add(b)});this.ea=new Promise((b,c)=>{"undefined"!==typeof wxSym&&b();const e=()=>{wxSymTag.removeEventListener("load",e);b()},g=()=>{wxSymTag.removeEventListener("error",g);c()};wxSymTag.addEventListener("load",e);wxSymTag.addEventListener("error",g)});this.ba=Promise.all([this.Y,this.ea]);this.S=this.b.getElementById("container");
this.R=this.b.getElementById("slideRoot");this.ca=this.b.getElementById("slideIndex");this.M=this.b.getElementById("carousel");this.g=this.b.getElementById("searchbar");this.c=this.b.getElementById("datebar");this.h=this.b.getElementById("messageArea");this.aa=this.b.getElementById("report");this.v=this.b.getElementById("queries__container");this.W=this.b.getElementById("back");this.j=this.c.nextElementSibling;this.da=b=>{function c(e){e.target===this&&"width"===e.propertyName&&(this.removeEventListener("transitionend",
c),this.removeEventListener("transitioncancel",c),b())}this.j.addEventListener("transitionend",c);this.j.addEventListener("transitioncancel",c)};this.A=()=>{var b=this.b.defaultView.innerWidth;this.i=b=Math.min(Y,b-2*Math.min(.06*b,30)+20,this.M.clientHeight);var c=this.u;c.width=b;c.height=b;this.b.documentElement.style.setProperty("--canvas-size",b+"px")};this.u=new Qa(this.b);this.P=qa(this.P,this);this.A();Xa(this)}P(a){this.aa.textContent=a}},Z="collapsed",Va="transition-all",Ya=a=>{requestAnimationFrame(a)},
Y=400,va="slide--check",wa="marked",Za="/static/check.svg",Ha="message--info",Fa="message--warning";const ab=new na,bb=new $a(document);(function(){var a=new La(ab,bb);M(a);Sa(a.b,a.f);a.b.W.addEventListener("click",a.c);Ta(a.b,()=>{a.model.g&&ua(a,I(a.model))})})();
